[phases.setup]
nixPkgs = ["python310", "python310Packages.pip"]
aptPkgs = ["libgl1"]

[phases.install]
cmds = ["pip install -r backend/requirements.txt"]

[phases.build]
cmds = []

[start]
cmd = "PYTHONPATH=/app python -m uvicorn backend.main:app --host 0.0.0.0 --port $PORT"
